watch_next/urls.py
from django.urls import path
from . import views

app_name = 'watch_next'

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('None', views.trailer, name='trailer')
]

watch_next/models.py
from django.db import models

# Create your models here.

watch_next/views.py
import spacy
import requests
import os

from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render

url = "https://api.themoviedb.org/3/search/multi"
api_key = "736ed3567de99709070b801464a1513f"  # Replace with your MovieDB API key

nlp = spacy.load('en_core_web_md')


def index(request):
    return render(request, 'watch_next/index.html')


def search_movies(query):
    query_params = {
        "api_key": api_key,
        "query": query
    }
    response = requests.get(url, params=query_params)
    if response.status_code == 200:
        data = response.json().get("results", [])
        for result in data:
            media_type = result.get("media_type")
            if media_type == "movie":
                return extract_movie_data(result)
            elif media_type == "tv":
                return extract_series_data(result)
    return None, None, None, None, None, None


def extract_movie_data(result):
    movie_title = result.get("title")
    movie_overview = result.get("overview")
    movie_rating = result.get("vote_average")
    movie_genre_ids = result.get("genre_ids")
    movie_poster = get_image_url(result.get("poster_path"))
    movie_trailer = get_movie_trailer(result.get("id"))
    return movie_title, movie_overview, movie_rating, movie_genre_ids, movie_poster, movie_trailer    


def extract_series_data(result):
    series_title = result.get("name")
    series_overview = result.get("overview")
    series_rating = result.get("vote_average")
    series_genre_ids = result.get("genre_ids")
    series_poster = get_image_url(result.get("poster_path"))
    series_trailer = get_series_trailer(result.get("id"))
    return series_title, series_overview, series_rating, series_genre_ids, series_poster, series_trailer


def get_image_url(image_path):
    if image_path:
        return f"https://image.tmdb.org/t/p/w500/{image_path}"
    else:
        default_image_path = "static/assets/img/popcorn.jpg"
        if os.path.exists(default_image_path):
            return default_image_path
    return None


"""def get_image_url(image_path):
    if image_path:
        return f"https://image.tmdb.org/t/p/w500/{image_path}"
    return "static/assets/img/popcorn.jpg"
    
"""
def get_movie_trailer(movie_id):
    trailer_url = f"https://api.themoviedb.org/3/movie/{movie_id}/videos"
    query_params = {"api_key": api_key}
    response = requests.get(trailer_url, params=query_params)

    if response.status_code == 200:
        data = response.json().get("results", [])
        for result in data:
            trailer_key = result.get("key")
            if trailer_key:
                return f"https://www.youtube.com/watch?v={trailer_key}"
    return None
    
    

def get_series_trailer(series_id):
    trailer_url = f"https://api.themoviedb.org/3/tv/{series_id}/videos"
    query_params = {"api_key": api_key}
    response = requests.get(trailer_url, params=query_params)
    if response.status_code == 200:
        data = response.json().get("results", [])
        for result in data:
            trailer_key = result.get("key")
            if trailer_key:
                return f"https://www.youtube.com/watch?v={trailer_key}"
            
    return None

def trailer(request):
    
        return render(request, 'watch_next/trailer.html')
  
    

def recommend_movies(movie_title, movie_overview, movie_rating, movie_genre_ids, movie_poster, movie_trailer):
    if movie_title is None:
        movie_title = "Title Unknown"

    query_params = {
        "api_key": api_key,
        "query": movie_title,
        "overview": movie_overview,
        "vote_average": movie_rating,
        "with_genres": ",".join(str(genre_id) for genre_id in movie_genre_ids)
    }
    response = requests.get(url, params=query_params)
    if response.status_code == 200:
        data = response.json().get("results", [])
        recommended_movies = []
        for result in data:
            title = result.get("title")
            overview = result.get("overview")
            rating = result.get("vote_average")
            poster = get_image_url(result.get("poster_path"))
            trailer = get_movie_trailer(result.get("id"))
            
            if overview is not None:
                similarity = nlp(movie_overview).similarity(nlp(overview))
                if title != movie_title and similarity > 0.7:
                    if title is None:
                        title = "We couldnt find thr title of the movie, sorry"
                    rating = round(rating, 1)
                    recommended_movies.append({
                        "title": title,
                        "overview": overview,
                        "rating": rating,
                        "poster": poster,
                        "trailer": trailer
                    })

        
        return sorted(recommended_movies, key=lambda x: x["rating"], reverse=True)[:3]
    
    return "No recommended movies found, sorry"
    

@csrf_exempt
def search(request):
    if request.method == 'POST':
        user_input = request.POST.get('series_or_movie')
        movie_title, movie_overview, movie_rating, movie_genre_ids, movie_poster, movie_trailer = search_movies(user_input)
        if movie_title:
            recommended_movies = recommend_movies(movie_title, movie_overview, movie_rating, movie_genre_ids, movie_poster, movie_trailer)
            movie_rating = round(movie_rating, 1) 
            
            context = {
                'movie_found': True,
                'movie_title': movie_title,
                'movie_overview': movie_overview,
                'movie_rating': movie_rating,
                'movie_genre_ids': movie_genre_ids,
                'movie_poster': movie_poster,
                'movie_trailer': movie_trailer,
                'recommended_movies': recommended_movies,
            }
            
            return render(request, 'watch_next/results.html', context)

        else:
            return HttpResponse("Movie not found, please try a different title ")

    return HttpResponse("Invalid request")

'''
                             THINGS TO FIX !!!
- RATING SHOULD BE ROUNDED OFF TO TWO DECIMAL PLACES
- IF THE TRAILER OF THE MOVIE IS NOT AVALABLE,REPLACE WITH A STRING
- POSTER IMAGE PLACEHOLDER, IF THE POSTER S NULL
'''

watch_next/templates/watch_next/index.html
<DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Watch Next</title>

    {% load static %}
    <!-- main styling sheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">


</head>

<body>

    <header class="header">
           <a href="#home" class="logo">Watch Next</a>
     
       <nav class="navbar">
            <a href="#home">Home</a>
            <a href="#about">About</a>
            <a href="#contact">Contact</a>
        </nav>

    </header>

    <section id="home" class="d-flex flex-column justify-content-center align-items-center">
		<div id="search-container">
        <h2 style="color: white">Search for a movie or series you like and we will recommend something for you 😎🎦🕶🍿</h2>

        <div id="container d-flex flex-column align-items-center">

            <div class="d-flex flex-column align-items-center">

                <form action="{% url 'watch_next:search' %}" method="post">
                    {% csrf_token %}
                    <input id="search" type="text" name="series_or_movie"placeholder="Search for movies/series  " id="search" class="search" required>
					<input type="submit" class="btn btn-primary register-btn" value="Search" />
                </form>
            </div>

        </div>
		</div>


    </section>
	
	
	

    <section id="about" class="d-flex flex-column justify-content-center align-items-center">
        <h1>About</h1>
        <br>
        <section>
            <h2>How It Works</h2>
            <ul>
                <li>
                    <strong>Search:</strong> Enter the title of a movie or series you enjoy in the search bar.
                </li>
                <li>
                    <strong>Discover:</strong> Explore the details of the found movie or series, including the title, overview, rating, and genre.
                </li>
                <li>
                    <strong>Recommendations:</strong> Get personalized recommendations based on the movie or series you searched for.
                    Our algorithm analyzes various factors to suggest similar titles that you might love.
                </li>
                <li>
                    <strong>Explore:</strong> Dive into the recommended movies and series, view their plots, ratings, and even watch their
                    trailers to find your next binge-worthy experience.
                </li>
            </ul>
        </section>

        <section>
            <h2>Our Technology</h2>
            <p>
                Watch Next utilizes advanced natural language processing (NLP) techniques powered by the Spacy library.
                By analyzing movie overviews and applying sophisticated algorithms, we can accurately suggest titles that align
                with your preferences.
            </p>
            <p>
                We leverage the power of the Movie Database API (TMDB) to access a vast collection of movie and series information, including
                plots, ratings, genres, posters, and trailers. This ensures that our recommendations are up-to-date and reflect the latest
                trends in the entertainment industry.
            </p>
        </section>

    </section>

    <section id="contact" class="d-flex flex-column justify-content-center align-items-center">
        <section>
            <h2 style="color: black;">Contact Us</h2>
            <p style="color: black;">We value your feedback! If you have any questions, suggestions, or encounter any issues while using Watch Next,
               please don't hesitate to reach out to us. You can contact our support
               team at: <a href="hrkodisang@gmail.com">hrkodisang@gmail.com</a>.
            </p>
        </section>
    </section>

    <footer id="footer">
        <div class="container">
            <div class="copyright">
                &copy; Copyright <span>2023</span>
            </div>

        </div>
    </footer><!-- End  Footer -->
	
	
	<!--btn script-->
	    <script src=" static/assets/js/scripts.js"></script>

</body>

</html>

watch_next/templates/watch_next/results.html
<DOCTYPE html>
<html lang="en">

<head>
    <title>Watch Next</title>

    {% load static %}
    <!-- main styling sheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">


</head>

<body>


<section id="result">
    {% if movie_found %}
        <h2 id="movie_title" style="text-align: center">Found: {{ movie_title }}</h2>
        <div id="movie-details">
            <div id="poster">
                <img src="{{ movie_poster }}" alt="No Poster Available" class="poster-image">
            </div>
            <div class="details">     
                <p id="movie_rating" style="text-align: center">⭐ {{ movie_rating }}</p>
                <p id="movie_overview" style="text-align: center">{{ movie_overview }}</p>
				
            </div>
				<h2 style="text-align: center"><a target = "_blank" href ="{{ movie_trailer }}">Watch trailer</a></h2>
        </div>
		
		<h2 style="text-align: center">Recommended</h2>
        <div class="recommended-movies">
				<div class="recommended-movie">
					{% for recommended_movie in recommended_movies %}
					<div class="recommended-movie-item">
					
					<div class="recommended_poster">
                        <img src="{{ recommended_movie.poster }}" alt="No Poster Available" class="recommended_poster-image">
						
					<div class="details">
                        <h4>{{ recommended_movie.title }}</h4>
                        <p>⭐ {{ recommended_movie.rating }}</p>
                        <p>{{ recommended_movie.overview }}</p>
						<h2><a target = "_blank" href ="{{ recommended_movie.trailer }}">Watch trailer</a></h2>
						
						</div>
					</div>
                    
					
                </div>
				
				    {% endfor %}
			</div>
		</div>
    {% else %}
        <h2>Movie or Series Not Found</h2>
        <p>We couldn't find any movie or series matching your search. Please try a different title.</p>
    {% endif %}
	<br>
	<div id="home-btn">
		<button><a href="{% url 'watch_next:index' %}" >HOME</a></button>
	</div>
	
	
</section>
			<!--btn script-->
	    <script src=" static/assets/js/scripts.js"></script>

</body>

</html>

watch_next/templates/watch_next/trailer.html
<DOCTYPE html>
<html lang="en">

<head>
    <title>Watch Next</title>

    {% load static %}
    <!-- main styling sheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">


</head>

<body>


<section id="trailer">
		<h1 style="text-align:center" >Trailer not available </h1>
		
		<div id="home-btn">
		<button><a href="{% url 'watch_next:index' %}" >HOME</a></button>
	</div>
   
</section>

</body>

</html>